---
proxy-providers:
#MODIFICATION By: SEKARREPKU edited by Daonah, (trakter latifan ja) 
  #CREDIT: REYRE,MASTERWIFI,PEJUANG RECEH,ALL MEMBER OPEN WRT
  #SUPPORT TRAKTER DANA OVO GOPAY SHOPEPAY 082225022058 BCA 7580612398 a/n LATIFAN

  Gaming:
    type: file
    path: "./proxy_provider/gaming1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Umum:
    type: file
    path: "./proxy_provider/umum1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Extraunli:
    type: file
    path: "./proxy_provider/extraunli1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Youtube:
    type: file
    path: "./proxy_provider/youtube1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Netflix:
    type: file
    path: "./proxy_provider/netflix.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Gaming
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - Gaming
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Umum
  type: load-balance
  disable-udp: false
  use:
  - Umum
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Extraunli
  type: load-balance
  disable-udp: false
  use:
  - Extraunli
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Youtube
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - Youtube
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Netflix
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - Netflix
  url: http://www.gstatic.com/generate_204
  interval: '300'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: reyre
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
ipv6: false
profile:
  store-selected: true
rules:
- RULE-SET,Youtube,Youtube
- RULE-SET,Netflix,Netflix
- RULE-SET,Umum,Umum
- RULE-SET,Extraunli,Extraunli
- RULE-SET,Gaming,Gaming
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,GLOBAL
rule-providers:
  Umum:
    type: file
    behavior: classical
    path: "./rule_provider/umum1.yaml"
  Extraunli:
    type: file
    behavior: classical
    path: "./rule_provider/extraunli1.yaml"
  Youtube:
    type: file
    behavior: classical
    path: "./rule_provider/youtube1.yaml"
  Netflix:
    type: file
    behavior: classical
    path: "./rule_provider/netflix.yaml"
  Gaming:
    type: file
    behavior: classical
    path: "./rule_provider/gaming1.yaml"
tproxy-port: 7895
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
